/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  category?:
    | "web-development"
    | "mobile-development"
    | "ui-ux-design"
    | "devops"
    | "career-tips"
    | "tutorials"
    | "tech-news"
    | "tools-resources"
    | "other";
  tags?: Array<string>;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & Code)
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  >;
  author?: string;
  authorImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  readingTime?: number;
  featured?: boolean;
  publishedAt?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Component = {
  _id: string;
  _type: "component";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  category?:
    | "buttons"
    | "forms"
    | "cards"
    | "navigation"
    | "modals"
    | "animations"
    | "layout"
    | "data-display"
    | "feedback"
    | "other";
  tags?: Array<string>;
  previewImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  previewCode?: Code;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & Code)
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  dependencies?: Array<string>;
  difficulty?: "beginner" | "intermediate" | "advanced";
  liveDemo?: string;
  codeRepository?: string;
  publishedAt?: string;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  personName?: string;
  personRole?: string;
  personImg?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  comment?: string;
};

export type Skill = {
  _id: string;
  _type: "skill";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  icon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  iconName?: string;
  color?: string;
  category?:
    | "Frontend"
    | "Backend"
    | "Mobile"
    | "Database"
    | "DevOps"
    | "AI & Machine Learning"
    | "MLOps";
  proficiency?: number;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  link?: string;
  code?: string;
  description?: string;
  technologies?: Array<string>;
  duration?: string;
  role?: string;
  achievements?: Array<string>;
  isAI?: boolean;
  playgroundUrl?: string;
  architectureDiagram?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  metrics?: Array<{
    label?: string;
    value?: string;
    _key: string;
  }>;
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  role?: string;
  company?: string;
  companyLink?: string;
  year?: string;
  description?: string;
  technologies?: Array<string>;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Profile = {
  _id: string;
  _type: "profile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  headline?: string;
  shortBio?: string;
  longBio?: string;
  profileImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  resume?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  socialLinks?: Array<{
    platform?: string;
    url?: string;
    iconName?: string;
    _key: string;
  }>;
  stats?: {
    experienceYears?: string;
    technologiesCount?: string;
    projectsCount?: string;
    clientSatisfaction?: string;
    tokensOrchestrated?: string;
    agentsDeployed?: string;
  };
  typewriterTexts?: Array<string>;
  keyStrengths?: Array<string>;
  techStackPreview?: Array<string>;
  experienceAreas?: {
    fullStack?: string;
    backend?: string;
    ai?: string;
    mobile?: string;
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Blog
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Component
  | Code
  | Testimonial
  | Skill
  | Project
  | Experience
  | SanityFileAssetReference
  | Profile
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: experiencesQuery
// Query: *[_type == "experience"] | order(year desc) {  _id,  role,  company,  companyLink,  year,  description,  technologies}
export type ExperiencesQueryResult = Array<{
  _id: string;
  role: string | null;
  company: string | null;
  companyLink: string | null;
  year: string | null;
  description: string | null;
  technologies: Array<string> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: projectsQuery
// Query: *[_type == "project"] {  _id,  title,  image {    asset->{      _id,      url    }  },  link,  code,  description,  technologies,  duration,  role,  achievements,  isAI,  playgroundUrl,  architectureDiagram {    asset->{      _id,      url    }  },  metrics}
export type ProjectsQueryResult = Array<{
  _id: string;
  title: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  link: string | null;
  code: string | null;
  description: string | null;
  technologies: Array<string> | null;
  duration: string | null;
  role: string | null;
  achievements: Array<string> | null;
  isAI: boolean | null;
  playgroundUrl: string | null;
  architectureDiagram: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  metrics: Array<{
    label?: string;
    value?: string;
    _key: string;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: testimonialsQuery
// Query: *[_type == "testimonial"] {  _id,  personName,  personRole,  personImg {    asset->{      _id,      url    }  },  comment}
export type TestimonialsQueryResult = Array<{
  _id: string;
  personName: string | null;
  personRole: string | null;
  personImg: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  comment: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: skillsQuery
// Query: *[_type == "skill"] {  _id,  name,  icon {    asset->{      _id,      url    }  },  iconName,  color,  category,  proficiency}
export type SkillsQueryResult = Array<{
  _id: string;
  name: string | null;
  icon: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  iconName: string | null;
  color: string | null;
  category:
    | "AI & Machine Learning"
    | "Backend"
    | "Database"
    | "DevOps"
    | "Frontend"
    | "MLOps"
    | "Mobile"
    | null;
  proficiency: number | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: profileQuery
// Query: *[_type == "profile"][0] {  _id,  name,  role,  headline,  shortBio,  longBio,  profileImage {    asset->{      _id,      url    }  },  resume {    asset->{      _id,      url    }  },  socialLinks,  stats,  typewriterTexts,  keyStrengths,  techStackPreview,  experienceAreas}
export type ProfileQueryResult = {
  _id: string;
  name: string | null;
  role: string | null;
  headline: string | null;
  shortBio: string | null;
  longBio: string | null;
  profileImage: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  resume: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  socialLinks: Array<{
    platform?: string;
    url?: string;
    iconName?: string;
    _key: string;
  }> | null;
  stats: {
    experienceYears?: string;
    technologiesCount?: string;
    projectsCount?: string;
    clientSatisfaction?: string;
    tokensOrchestrated?: string;
    agentsDeployed?: string;
  } | null;
  typewriterTexts: Array<string> | null;
  keyStrengths: Array<string> | null;
  techStackPreview: Array<string> | null;
  experienceAreas: {
    fullStack?: string;
    backend?: string;
    ai?: string;
    mobile?: string;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: componentsQuery
// Query: *[_type == "component"] | order(publishedAt desc) {  _id,  title,  slug,  description,  category,  tags,  previewImage {    asset->{      _id,      url    }  },  difficulty,  publishedAt}
export type ComponentsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  category:
    | "animations"
    | "buttons"
    | "cards"
    | "data-display"
    | "feedback"
    | "forms"
    | "layout"
    | "modals"
    | "navigation"
    | "other"
    | null;
  tags: Array<string> | null;
  previewImage: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  difficulty: "advanced" | "beginner" | "intermediate" | null;
  publishedAt: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: componentBySlugQuery
// Query: *[_type == "component" && slug.current == $slug][0] {  _id,  title,  slug,  description,  category,  tags,  previewImage {    asset->{      _id,      url    }  },  previewCode,  content,  dependencies,  difficulty,  liveDemo,  codeRepository,  publishedAt}
export type ComponentBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  category:
    | "animations"
    | "buttons"
    | "cards"
    | "data-display"
    | "feedback"
    | "forms"
    | "layout"
    | "modals"
    | "navigation"
    | "other"
    | null;
  tags: Array<string> | null;
  previewImage: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  previewCode: Code | null;
  content: Array<
    | ({
        _key: string;
      } & Code)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  dependencies: Array<string> | null;
  difficulty: "advanced" | "beginner" | "intermediate" | null;
  liveDemo: string | null;
  codeRepository: string | null;
  publishedAt: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: blogsQuery
// Query: *[_type == "blog"] | order(publishedAt desc) {  _id,  title,  slug,  excerpt,  category,  tags,  coverImage {    asset->{      _id,      url    }  },  author,  authorImage {    asset->{      _id,      url    }  },  readingTime,  featured,  publishedAt}
export type BlogsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  category:
    | "career-tips"
    | "devops"
    | "mobile-development"
    | "other"
    | "tech-news"
    | "tools-resources"
    | "tutorials"
    | "ui-ux-design"
    | "web-development"
    | null;
  tags: Array<string> | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  author: string | null;
  authorImage: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  readingTime: number | null;
  featured: boolean | null;
  publishedAt: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: blogBySlugQuery
// Query: *[_type == "blog" && slug.current == $slug][0] {  _id,  title,  slug,  excerpt,  category,  tags,  coverImage {    asset->{      _id,      url    }  },  content,  author,  authorImage {    asset->{      _id,      url    }  },  readingTime,  featured,  publishedAt}
export type BlogBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  category:
    | "career-tips"
    | "devops"
    | "mobile-development"
    | "other"
    | "tech-news"
    | "tools-resources"
    | "tutorials"
    | "ui-ux-design"
    | "web-development"
    | null;
  tags: Array<string> | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  content: Array<
    | ({
        _key: string;
      } & Code)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  > | null;
  author: string | null;
  authorImage: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  readingTime: number | null;
  featured: boolean | null;
  publishedAt: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "experience"] | order(year desc) {\n  _id,\n  role,\n  company,\n  companyLink,\n  year,\n  description,\n  technologies\n}': ExperiencesQueryResult;
    '*[_type == "project"] {\n  _id,\n  title,\n  image {\n    asset->{\n      _id,\n      url\n    }\n  },\n  link,\n  code,\n  description,\n  technologies,\n  duration,\n  role,\n  achievements,\n  isAI,\n  playgroundUrl,\n  architectureDiagram {\n    asset->{\n      _id,\n      url\n    }\n  },\n  metrics\n}': ProjectsQueryResult;
    '*[_type == "testimonial"] {\n  _id,\n  personName,\n  personRole,\n  personImg {\n    asset->{\n      _id,\n      url\n    }\n  },\n  comment\n}': TestimonialsQueryResult;
    '*[_type == "skill"] {\n  _id,\n  name,\n  icon {\n    asset->{\n      _id,\n      url\n    }\n  },\n  iconName,\n  color,\n  category,\n  proficiency\n}': SkillsQueryResult;
    '*[_type == "profile"][0] {\n  _id,\n  name,\n  role,\n  headline,\n  shortBio,\n  longBio,\n  profileImage {\n    asset->{\n      _id,\n      url\n    }\n  },\n  resume {\n    asset->{\n      _id,\n      url\n    }\n  },\n  socialLinks,\n  stats,\n  typewriterTexts,\n  keyStrengths,\n  techStackPreview,\n  experienceAreas\n}': ProfileQueryResult;
    '*[_type == "component"] | order(publishedAt desc) {\n  _id,\n  title,\n  slug,\n  description,\n  category,\n  tags,\n  previewImage {\n    asset->{\n      _id,\n      url\n    }\n  },\n  difficulty,\n  publishedAt\n}': ComponentsQueryResult;
    '*[_type == "component" && slug.current == $slug][0] {\n  _id,\n  title,\n  slug,\n  description,\n  category,\n  tags,\n  previewImage {\n    asset->{\n      _id,\n      url\n    }\n  },\n  previewCode,\n  content,\n  dependencies,\n  difficulty,\n  liveDemo,\n  codeRepository,\n  publishedAt\n}': ComponentBySlugQueryResult;
    '*[_type == "blog"] | order(publishedAt desc) {\n  _id,\n  title,\n  slug,\n  excerpt,\n  category,\n  tags,\n  coverImage {\n    asset->{\n      _id,\n      url\n    }\n  },\n  author,\n  authorImage {\n    asset->{\n      _id,\n      url\n    }\n  },\n  readingTime,\n  featured,\n  publishedAt\n}': BlogsQueryResult;
    '*[_type == "blog" && slug.current == $slug][0] {\n  _id,\n  title,\n  slug,\n  excerpt,\n  category,\n  tags,\n  coverImage {\n    asset->{\n      _id,\n      url\n    }\n  },\n  content,\n  author,\n  authorImage {\n    asset->{\n      _id,\n      url\n    }\n  },\n  readingTime,\n  featured,\n  publishedAt\n}': BlogBySlugQueryResult;
  }
}
