import Head from 'next/head'
import Header from '../components/Header'
import AboutSection from '../components/AboutSection'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Footer from '../components/Footer'
import Testimonials from '../components/Testimonials'
import HeroSection from '../components/HeroSection'
import Contact from '../components/contacts'
import Script from 'next/script'
import MiscSkills from '../components/MiscSkills'

export default function Home() {
  return (
    <div className="text-white bg-black">
      <Head>
        <title>Aman Soni</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@400;500&family=Josefin+Sans:wght@100;400&family=Playfair+Display:wght@500;600&family=Poppins:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://unpkg.com/swiper@8/swiper-bundle.min.css"
        />
      </Head>
      <Script src="https://unpkg.com/@rive-app/webgl" />

      <Script src="https://unpkg.com/swiper@8/swiper-bundle.min.js" />

      {/* Header */}
      <Header />

      {/* Home Section */}
      <HeroSection />

      {/* About Section */}
      <AboutSection />

      {/* Skills Section */}
      <Skills />

      {/* Misc Skills */}
      <MiscSkills />

      {/* Projects Section */}
      <Projects />

      {/*  Testimonials */}
      <Testimonials />

      {/* Contacts */}
      <Contact />

      {/* Footer */}
      <Footer className="invisible" />

      {/* JSX for Fonts */}
      <style jsx global>{`
        html,
        body {
          padding: 0;
          margin: 0;
          font-family: Poppins, sans-serif;
        }

        * {
          box-sizing: border-box;
        }
      `}</style>
    </div>
  )
}
