import Head from "next/head";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Aman Soni</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
          rel="stylesheet"
        />
      </Head>

      {/* Header */}
      <Header />

      {/* Nav */}
      <div className={styles.nav} />

      {/* Intro Banner */}
      <div className="object-contains bg-blue-bg-purple-600 bg-opacity-75 h-100 p-20 w-100">
        <div class="grid grid-cols-2 gap-6">
          <div className="">
            <p className="text-blue-500 font-bold text-4xl pr-20  pt-30 colors.blue">
              I build & craft amazing experiences
            </p>
            <p className="text-blue-500 text-xl colors.blue pt-10">
              My name's Aman Soni. I craft user interfaces using modern frontend
              framework's such as Flutter, React and other web technologie's.
            </p>
          </div>
          <div>
            <div class="bg-rose-300">
              <img
                src="./images/svg/cool.jpg"
                class="object-contain h-62 w-full"
              ></img>
            </div>
          </div>
        </div>
      </div>

      {/* JSX for Fonts */}
      <style jsx global>{`
        html,
        body {
          padding: 0;
          margin: 0;
          font-family: Poppins;
        }

        * {
          box-sizing: border-box;
        }
      `}</style>
    </div>
  );
}
